<a href="https://colab.research.google.com/github/giankarlesguerra/Numerical-Methods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and its Operation


In [26]:
import numpy as np

In [12]:
a = np.array([1,2,3]) # 1 by 3 array
a[0]=4
print(a)


[4 2 3]


In [13]:
b = np.array([[1,2,3],[4,5,6]]) # 2 by 3 matrix
print(b.shape)
b [0,0]=7
print(b)

(2, 3)
[[7 2 3]
 [4 5 6]]


In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #sample of square matrix 3x3
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
d = np.full((2,2),4)
print(d)

[[4 4]
 [4 4]]


In [22]:
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [23]:
f = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(f)

[1 5 9]


In [29]:
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e+g)


[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
