<a href="https://colab.research.google.com/github/giankarlesguerra/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Matrix and Its Operations**

In [2]:
import numpy as np

$$A = \begin{bmatrix} -5 & 0 \\4 & 1 \\\end{bmatrix} , B = \begin{bmatrix} 6 & -3\\2 & 3\\\end{bmatrix} $$

In [11]:
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])

print(A)
print(B)
print(A.shape)
print(B.shape)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
(2, 2)
(2, 2)


**1. sum = A +B**

In [12]:
sum = (A + B)
print(sum)

[[ 1 -3]
 [ 6  4]]


**2.difference1 = B - A**

In [14]:
difference1 = (B - A)
print(difference1)

[[11 -3]
 [-2  2]]


**3.difference2 = A - B**

In [15]:
difference2 = (A - B)
print(difference2)

[[-11   3]
 [  2  -2]]
